from typing import Dict


ROLE_DESCRIPTIONS: Dict[str, str] = {
    "Retributionist": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** **2 uses.** Use `!reanimate <corpse> <target>` (or `!reanimate <corpse> <target1> <target2>` for Transporter) to use a dead Town member's ability for the night.\n> **Notes:** You cannot use hidden corpses. Each corpse may only be used once.",
    "Doctor": "> **Faction:** Town\n> **Stats:** No Attack / Basic Defense (self-heal)\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!heal <number>` to protect someone. You may heal yourself **once** per game. You cannot heal a revealed Mayor.",
    "Sheriff": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!investigate <number>` to learn if your target seems **innocent** or **suspicious**.\n> **Notes:** Framed targets read as suspicious. Doused targets read as suspicious.",
    "Investigator": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!investigate <number>` to receive a **list of possible roles** for your target (ToS-style).",
    "Lookout": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!watch <number>` to see who visits that player.",
    "Tracker": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!track <number>` to learn who your target visited.",
    "Vigilante": "> **Faction:** Town\n> **Stats:** Basic Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** You have **1 bullet**. Use `!shoot <number>`. If your shot kills a Town member, you will die of guilt the **next day**.",
    "Bodyguard": "> **Faction:** Town\n> **Stats:** Basic Attack / Basic Defense (self-protect)\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** `!protect <number>` once. If your target is attacked, you counter-kill the attacker and both die. You may self-protect once per game.",
    "Escort": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!roleblock <number>` to prevent their night action.",
    "Scary Grandma": "> **Faction:** Town\n> **Stats:** Basic Attack / Basic Defense (on alert)\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** **2 alerts.** Use `!alert` to go on guard. Anyone who visits you will be shot.",
    "Transporter": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** Each night, `!transport <number1> <number2>` to swap their locations.",
    "Mayor": "> **Faction:** Town\n> **Stats:** No Attack / No Defense\n> **Goal:** Lynch every criminal and evildoer.\n> **Abilities:** During the day, `!reveal` to show your role. Once revealed, your vote counts as **two**. Cannot be healed after revealing.",
    "Mobster": "> **Faction:** Mafia\n> **Stats:** Basic Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** Each night, `!kill <number>`.",
    "Consort": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** You are the Mafia's roleblocker. Each night, `!roleblock <number>`.",
    "Framer": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** Nights 1 and 2 only: `!frame <number>`. Investigators will see your target as suspicious.",
    "Gravedigger": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** **1 use.** `!hide <number>`. If they die, their role is hidden from the Town.",
    "Hypnotist": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** Each night, `!hypnotize <number> <type>` to send a fake message. Types: `healed`, `roleblocked`, `transported`, `controlled`, `attacked`.",
    "Mole": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** **1 use.** `!investigate <number>` to learn their exact role.",
    "Tailor": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** **1 use.** `!tailor <number> <fake_role>` to fake their death role.",
    "Gatekeeper": "> **Faction:** Mafia\n> **Stats:** No Attack / No Defense\n> **Goal:** Gain majority control of the Town.\n> **Abilities:** **2 uses.** Each night, `!guard <number>`. Non-Mafia visitors to your target will be roleblocked.",
    "Chaos": "> **Faction:** Neutral (Chaotic)\n> **Stats:** No Attack / No Defense\n> **Goal:** Survive to the end of the game.\n> **Abilities:** **2 uses.** Use `!chaos <number1> <number2>`. You will secretly cause a random disruptive effect involving your targets.\n> **Notes:** Some Chaos effects may send you normal feedback (for example, investigations or visit info).",
    "Jester": "> **Faction:** Neutral (Evil)\n> **Stats:** Unstoppable Attack / No Defense\n> **Goal:** Get yourself lynched by the Town.\n> **Abilities:** If lynched, you win and `!haunt` one of the players who voted **guilty** or **abstained**.",
    "Executioner": "> **Faction:** Neutral (Evil)\n> **Stats:** No Attack / No Defense\n> **Goal:** Get your assigned target lynched.\n> **Abilities:** If your target is killed at night, you become a Jester.",
    "Survivor": "> **Faction:** Neutral (Benign)\n> **Stats:** No Attack / No Defense (Basic while vested)\n> **Goal:** Survive to the end of the game.\n> **Abilities:** **2 vests.** Use `!vest` at night to gain Basic defense for the night. If you are roleblocked, your vest will not be used.",
    "Witch": "> **Faction:** Neutral (Evil)\n> **Stats:** No Attack / Night 1 Defense\n> **Goal:** Survive to see the Town lose.\n> **Abilities:** Each night, `!control <number1> <number2>` to force the first target to act on the second. You learn their role.\n> **Notes:** Immune to standard roleblocks (Escort/Consort), but the Gatekeeper can still block visitors to a guarded target.",
    "Pirate": "> **Faction:** Neutral (Evil)\n> **Stats:** Basic Attack / No Defense\n> **Goal:** Win 2 plunder duels.\n> **Abilities:** Each night, `!plunder <number>` for a rock-paper-scissors duel. Win 2 duels to win the game (you can still win even if you later die). You roleblock your target regardless of outcome.",
    "Arsonist": "> **Faction:** Neutral (Killing)\n> **Stats:** Unstoppable Attack / Basic Defense\n> **Goal:** Kill everyone who would oppose you.\n> **Abilities:** Each night, `!douse <number>`, or use `!clean` to remove gasoline from yourself. At any time, `!ignite` to kill all doused players. You and doused players appear suspicious to investigators.\n> **Notes:** If you are doused, igniting will burn you too unless you clean first.",
}


def get_role_description(role: str) -> str:
    return ROLE_DESCRIPTIONS.get(role, "You seem to have a role that defies description.")
